
### POST request with full JSON body
POST http://127.0.0.1:5000/resume
Content-Type: application/json

{
    "name": "John Doe",
    "tagline": "Experienced software engineer with a passion for coding.",
    "email": "john.doe@example.com",
    "phone": "123-456-7890",
    "address": "123 Main St, Anytown, USA",
    "socialLinks": {
      "linkedin": "https://www.linkedin.com/in/johndoe",
      "twitter": "https://twitter.com/johndoe",
      "github": "https://github.com/johndoe"
    },
    "objective": "To contribute to the success of a forward-thinking company with my skills and experience as a software engineer.",
    "education": [
      {
        "degree": "B.S. in Computer Science",
        "institution": "University of Example",
        "years": "2010-2014"
      }
    ],
    "experience": [
      {
        "jobTitle": "Senior Software Engineer",
        "company": "Example Company",
        "years": "2014-Present"
      }
    ],
    "skills": ["Python", "JavaScript", "C++", "HTML", "CSS", "SQL", "Git"]
}


### GET request
GET http://127.0.0.1:5000/resume

### PUT request with updated full JSON body
PUT http://127.0.0.1:5000/resume
Content-Type: application/json

{
    "name": "John Doe",
    "tagline": "Experienced software engineer with a passion for coding.",
    "email": "john.doe@example.com",
    "phone": "123-456-7890",
    "address": "123 Main St, Anytown, USA",
    "socialLinks": {
      "linkedin": "https://www.linkedin.com/in/johndoe",
      "twitter": "https://twitter.com/johndoe",
      "github": "https://github.com/johndoe"
    },
    "objective": "To contribute to the success of a forward-thinking company with my skills and experience as a software engineer.",
    "education": [
      {
        "degree": "B.S. in Computer Science",
        "institution": "University of Example",
        "years": "2010-2014"
      }
    ],
    "experience": [
      {
        "jobTitle": "Junior Software Engineer",
        "company": "Example Company",
        "years": "2014-Present"
      }
    ],
    "skills": ["Python", "JavaScript", "C++", "HTML", "CSS", "SQL", "Git"]
}


### DELETE request
DELETE http://127.0.0.1:5000/resume
